# Generated by Django 3.1.1 on 2020-11-10 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_listing_app', '0002_auto_20201110_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller_product',
            name='rating',
        ),
    ]
