# Generated by Django 3.1.1 on 2020-12-14 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_listing_app', '0002_auto_20201214_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='plan_desc',
            field=models.TextField(default=''),
        ),
    ]
