# Generated by Django 3.1.1 on 2020-11-10 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_listing_app', '0003_remove_seller_product_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_type', models.CharField(max_length=60)),
            ],
        ),
        migrations.AlterField(
            model_name='seller_product',
            name='car_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_listing_app.car_type'),
        ),
    ]
