# Generated by Django 3.1.1 on 2020-11-10 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_listing_app', '0004_auto_20201110_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller_product',
            name='car_speed',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
